config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: ""
  devise_for :views
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index'
  resources :posts, path: ""

  resources :posts do
    member do
      put 'switch'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :item, presence: true
  validates :user, presence: true
  validates :item, length: {in: 1..20} 
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatables
  has_many :posts
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create,:edit,:update, :switch, :destroy, :index]
  before_action :set_post, only: [:update, :switch, :destroy]

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path
    else
      render "index"
    end
  end

  def index
    if params[:id].present?
      @post = Post.find(params[:id])
    else
      @post = Post.new
    end
    @posts = Post.where(user_id: current_user.id, switch: 0)
    @done = Post.where(user_id: current_user.id, switch: 1)
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path
    else
      render "index"
    end
  end

  def switch
    @post.user_id = current_user.id
    if @post.switch == 0
      @post.update(switch: 1)
      redirect_to posts_path
    else
      @post.update(switch: 0)
      redirect_to posts_path
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end


  private

  def post_params
    params.require(:post).permit(:item, :switch, :user_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
   :user
 end

 def resource
   @resource ||= User.new
 end

 def devise_mapping
   @devise_mapping ||= Devise.mappings[:user]
 end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>

    <title>Lista</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="body clearfix">
    <header class="header clearfix">
      <h1 class="logo">
      </h1>
      <nav class="header_nav clearfix">
        <% if user_signed_in? %>
            <%= link_to 'プロフィール', "", class: :"menu-item link-to-edit", return: "false" %>
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: :"menu-item" %>
        <% else %>
            <%= link_to '新規登録', new_user_registration_path, class: :"menu-item" %>
            <%= link_to 'ログイン', new_user_session_path, class: :"menu-item" %>
        <% end %>
      </nav>
    </header>

    <%= yield %>

  </body>

  <script>
    $(".link-to-edit").click(function(){
      $(".sessions_edit").fadeToggle()
      return false
    })

    $(".body").click(function(){
      $(".sessions_edit").fadeOut()
    })

    $(".list_content-item-link").click(function(){
      $(this).next("ul").stop().slideToggle();
      return false
    })

    var v = $("#post_item").val();
    $("#post_item").val("");
    $("#post_item").focus().val(v);

  </script>

</html>

app/views/posts/index.html.erb
<div class="list">
  <p class="list_title">
    達成したいこと
  </p>
  <ol class="list_content">
    <% @posts.each do |post| %>
      <li class="list_content-item">
        <p class="list_content-item-link"><%= post.item %></p>
        <ul class="list_content-item-list clearfix">
          <li class="list_content-item-list-item" id="post-<%= post.id %>" data-post-id="<%= post.id %>">
            <%= link_to "達成", switch_post_path(post.id), method: :put, remote: true %>
          </li>
          <li class="list_content-item-list-item">
            <%= link_to "編集", posts_path(id: post.id) %>
          </li>
          <li class="list_content-item-list-item">
            <%= link_to "削除", post_path(post), method: :delete, remote: true %>
          </li>
        </ul>
      </li>
    <% end %>
  </ol>

  <%= form_for(@post, remote: true) do |post| %>
    <%= post.text_field :item, placeholder: :"ここに入力…（20字以内）", autocomplete: "off" %>
  <% end %>

</div>

<div class="list">
  <p class="list_title">
    達成したこと
  </p>
  <ol class="list_content">
    <% @done.each do |post| %>
      <li class="list_content-item">
        <p class="list_content-item-link"><%= post.item %></p>
        <ul class="list_content-item-list clearfix">
          <li class="list_content-item-list-item" id="post-<%= post.id %>" data-post-id="<%= post.id %>">
            <%= link_to "戻す", switch_post_path(post.id), method: :put, remote: true %>
          </li>
          <li class="list_content-item-list-item">
            <%= link_to "編集", posts_path(id: post.id), remote: true %>
          </li>
          <li class="list_content-item-list-item">
            <%= link_to "削除", post_path(post), method: :delete, remote: true %>
          </li>
        </ul>
      </li>
    <% end %>
  </ol>

</div>

<%= render :partial => "devise/registrations/edit" %>